# Change these first
owner: adroitcreations-dev # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository
timezone: Pacific/Auckland

sites:
  - name: Yorke Peninsula Council
    url: https://yorke.sa.gov.au/
  - name: Yorke elementOrg
    url: https://yorke.elementorg.com
  - name: The Creation Room
    url: https://thecreationroom.com/
  - name: Status page - elementOrg
    url: https://status.elementorg.com
    __dangerous__disable_verify_peer: true
  - name: NGSC elementORG
    url: https://ngsc.elementorg.com
  - name: elementTime website
    url: https://www.elementtime.com/
  - name: elementTime
    url: https://yorke.elementtime.com/validate
  - name: elementStaff - york
    url: https://yorke.elementstaff.com
  - name: elementStaff - www
    url: http://www.elementstaff.com
  - name: elementStaff2
    url: https://testyorke.elementstaff.com/api/health
  - name: elementRec 
    url: https://mountbarker.elementrec.com/apis/system/health
  - name: Adroit Creations website
    url: https://www.adroitcreations.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Adroit Creations
  introTitle: "System Status"
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
